server:
  port: 8080
  host: 0.0.0.0

holidayDataService:
  baseURI: "https://date.nager.at/api/v3/"
  pathFormat: "/publicholidays/%04d/%.2s"

maxFollowingYearsChecked: 2

apikey: "password"

security:
  providers:
  - http-basic-auth:
      realm: "shared-holiday"
      users:
      - login: ""
        password: ${apikey}
        roles: ["user"]
security.web-server:
  defaults:
    authenticate: true